import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { cache } from "react";
import { StoryMessage } from "@/components/story/StoryMessage";
import { StoryPlayer } from "@/components/story/StoryPlayer";
import { getConcept, type ConceptRecord } from "@/lib/data/concepts";
import { BUNDLED_FIXTURES } from "@/lib/fixtures";
import { conceptToStory } from "@/lib/story/from-concept";

// One database read per request, shared by metadata and the page.
const load = cache((id: string) => getConcept(id));

const dateFormat = new Intl.DateTimeFormat("en", { dateStyle: "medium", timeZone: "UTC" });

export async function generateMetadata({ params }: PageProps<"/concept/[id]">): Promise<Metadata> {
  const { id } = await params;
  const result = await load(id);
  if (result.status !== "ok") {
    return { title: "Explanation unavailable", robots: { index: false, follow: false } };
  }
  const { concept, origin } = result.record;
  const description = `${origin === "ai_generated" ? "AI-generated interactive explanation. " : ""}${concept.description}`;
  return { title: concept.title, description, openGraph: { title: concept.title, description, type: "article" } };
}

/** How the explanation was made, said plainly as the story's last caption. */
function closingNote(record: ConceptRecord): string | undefined {
  if (record.origin === "curated") return undefined;
  const model = record.generationMeta?.models?.generator;
  const attempts = record.generationMeta?.attempts;
  return [
    `Generated by AI${record.sourceTopic ? ` from “${record.sourceTopic}”` : ""} on ${dateFormat.format(new Date(record.createdAt))}${model ? ` with ${model}` : ""}.`,
    `It passed automated structure checks and an AI review${attempts ? ` on attempt ${attempts}` : ""}.`,
    "Automated review is not proof of accuracy and no sources were consulted, so verify important details.",
  ].join(" ");
}

export default async function ConceptPage({ params }: PageProps<"/concept/[id]">) {
  const { id } = await params;
  const result = await load(id);

  switch (result.status) {
    case "not_found":
      notFound();
    case "unconfigured": {
      const fixture = BUNDLED_FIXTURES.find((f) => f.concept.id === id);
      return (
        <StoryMessage
          title="The database isn't configured"
          action={fixture ? { href: `/demo/${fixture.slug}`, label: `Open the bundled copy: ${fixture.concept.title}` } : undefined}
        >
          This server has no Supabase connection, so saved explanations can&apos;t be loaded.
        </StoryMessage>
      );
    }
    case "invalid":
      return (
        <StoryMessage title="This explanation can't be displayed">
          Its stored data didn&apos;t pass validation, so it isn&apos;t shown. Nothing is wrong with your browser; the record needs
          to be repaired or generated again.
        </StoryMessage>
      );
    case "error":
      return (
        <StoryMessage title="We couldn't load this explanation" action={{ href: `/concept/${id}`, label: "Try again" }}>
          The database didn&apos;t respond.
        </StoryMessage>
      );
    case "ok": {
      const { record } = result;
      const generated = record.origin === "ai_generated";
      return (
        <StoryPlayer
          story={conceptToStory(record.concept, {
            subtitle: generated ? "AI-generated explanation" : "Curated explanation",
            closing: closingNote(record),
          })}
          label={generated ? "AI-generated" : "Curated"}
        />
      );
    }
  }
}
