import { randomUUID } from "node:crypto";
import { expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { SseParser } from "@/lib/sse/parser";

/**
 * Live generation path with a MOCKED model provider: real Next.js server in
 * live mode, real rate limiting, real persistence and RLS. Only OpenAI is
 * replaced, by scripts/mock-openai.ts. This is not a live OpenAI smoke test.
 *
 * There are no accounts, and the database keeps rows from earlier runs, so the
 * gallery checks compare the set of card links before and after each action.
 */
const LIVE = process.env.E2E_LIVE_BASE_URL;
const MOCK = process.env.E2E_MOCK_OPENAI_URL ?? "http://127.0.0.1:4010";

test.skip(!LIVE, "Set E2E_LIVE_BASE_URL to run the live-mode specs (see README).");
test.use({ baseURL: LIVE });
test.describe.configure({ mode: "serial" });

let page: Page;
let firstConceptUrl = "";

/** Links of the mock provider's cards in Explore, after loading the home page. */
async function mockCardLinks(): Promise<Set<string>> {
  await page.goto("/");
  const links = page.getByRole("region", { name: "Explore" }).getByRole("link", { name: /\(mock provider\)/ });
  return new Set(await links.evaluateAll((anchors) => anchors.map((a) => a.getAttribute("href") ?? "")));
}

const added = (before: Set<string>, after: Set<string>) => [...after].filter((href) => !before.has(href));

async function lastEvent(body: Buffer) {
  const parser = new SseParser();
  return [...parser.feed(body), ...parser.end()].map((m) => JSON.parse(m.data)).at(-1);
}

const mockCalls = async (request: APIRequestContext) =>
  (await (await request.get(`${MOCK}/__calls`)).json()) as Array<{ schema: string; repair: boolean; strict: boolean; store: unknown }>;

async function generate(topic: string) {
  await page.goto("/");
  await page.getByLabel("What complex concept should we visualize today?").fill(topic);
  await page.getByRole("button", { name: "Visualize" }).click();
}

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage();
});

test.afterAll(async () => {
  await page.close();
});

test("there are no accounts: anyone can generate", async () => {
  await page.goto("/");
  await expect(page.getByText(/New explanations are public/)).toBeVisible();
  await expect(page.getByRole("link", { name: /sign in/i })).toHaveCount(0);
  expect((await page.request.get("/login")).status()).toBe(404);
});

test("generates, repairs once, persists, then navigates to the saved explanation", async ({ request }) => {
  await request.delete(`${MOCK}/__calls`);
  await generate("Binary search");

  const loader = page.getByTestId("generation-loader");
  await expect(loader).toContainText("Attempt 2 of 3", { timeout: 20_000 });
  await expect(loader).toContainText("Attempt 1 was sent back for revision");
  await expect(loader).toContainText("not a node in this step");

  await page.waitForURL(/\/concept\/[0-9a-f-]{36}$/, { timeout: 30_000 });
  firstConceptUrl = page.url();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Binary search (mock provider)");
  await expect(page.getByText("AI-generated", { exact: true })).toBeVisible();
  // How it was made is the story's last caption.
  for (let i = 0; i < 200 && !(await page.getByRole("button", { name: "Start over" }).isVisible()); i++) {
    await page.keyboard.press("ArrowRight");
  }
  const closing = page.locator("p[aria-live]");
  await expect(closing).toContainText("Generated by AI from “Binary search”");
  await expect(closing).toContainText("on attempt 2");

  const calls = await mockCalls(request);
  expect(calls.map((c) => `${c.schema}${c.repair ? "+repair" : ""}`)).toEqual([
    "teaching_plan",
    "concept_scenes",
    "concept_scenes+repair",
    "concept_review",
  ]);
  expect(calls.every((c) => c.strict && c.store === false)).toBe(true);
});

test("the saved explanation is reachable again by URL and listed publicly", async () => {
  await page.goto(firstConceptUrl);
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Binary search (mock provider)");
  await page.getByRole("button", { name: /^Continue/ }).click();
  await expect(page.locator("p[aria-live]")).not.toBeEmpty();
  expect(await mockCardLinks()).toContain(new URL(firstConceptUrl).pathname);
});

test("another visitor can open the explanation", async ({ browser }) => {
  const stranger = await browser.newPage();
  await stranger.goto(firstConceptUrl);
  await expect(stranger.getByRole("heading", { level: 1 })).toHaveText("Binary search (mock provider)");
  await stranger.close();
});

test("a draft that never passes review is not saved", async ({ request }) => {
  const before = await mockCardLinks();
  await request.delete(`${MOCK}/__calls`);
  await generate("Binary search always-reject");
  const alert = page.getByTestId("generation-loader").getByRole("alert");
  await expect(alert).toContainText("No draft passed the checks", { timeout: 30_000 });
  await expect(alert).toContainText("The middle index is computed incorrectly.");
  const calls = await mockCalls(request);
  expect(calls.filter((c) => c.schema === "concept_scenes")).toHaveLength(3);
  expect(added(before, await mockCardLinks())).toEqual([]);
});

test("an unsupported topic gets the planner's explanation", async () => {
  await generate("Stock charts unsupported");
  const alert = page.getByTestId("generation-loader").getByRole("alert");
  await expect(alert).toContainText("This topic doesn't fit the format");
  await expect(alert).toContainText("needs charts");
});

test("cancelling stops the server work, saves nothing, and frees the slot", async () => {
  const before = await mockCardLinks();
  await generate("Binary search slow");
  const loader = page.getByTestId("generation-loader");
  await expect(loader).toContainText("Draft scenes", { timeout: 10_000 });
  await expect(loader.getByText("Drafting scenes from the plan").first()).toBeVisible();
  await loader.getByRole("button", { name: "Cancel" }).click();
  await expect(loader).toContainText("Generation cancelled");

  // The lease is released when the server notices the disconnect.
  let createdId = "";
  await expect
    .poll(async () => {
      const response = await page.request.post("/api/generate", {
        data: { topic: "Binary search", idempotencyKey: randomUUID() },
      });
      const status = response.status();
      if (status === 200) createdId = (await lastEvent(await response.body())).conceptId;
      return status;
    }, { timeout: 10_000 })
    .toBe(200);

  // Only the explanation just created through the API is new; nothing from the cancelled run.
  expect(added(before, await mockCardLinks())).toEqual([`/concept/${createdId}`]);
});

test("a repeated request with the same idempotency key returns the saved result without regenerating", async ({ request }) => {
  const key = randomUUID();
  const run = async () => {
    const response = await page.request.post("/api/generate", { data: { topic: "Binary search", idempotencyKey: key } });
    expect(response.headers()["content-type"]).toContain("text/event-stream");
    return lastEvent(await response.body());
  };
  const first = await run();
  expect(first).toMatchObject({ type: "completed", persisted: true });
  await request.delete(`${MOCK}/__calls`);
  const second = await run();
  expect(second).toMatchObject({ type: "completed", conceptId: first.conceptId });
  expect(await mockCalls(request)).toEqual([]);
});
