import { randomUUID } from "node:crypto";
import { expect, test, type APIRequestContext, type Page } from "@playwright/test";

/**
 * Live generation path with a MOCKED model provider: real Next.js server in
 * live mode, real rate limiting, and the real browser library (localStorage).
 * Only OpenAI is replaced, by scripts/mock-openai.ts. This is not a live
 * OpenAI smoke test.
 */
const LIVE = process.env.E2E_LIVE_BASE_URL;
const MOCK = process.env.E2E_MOCK_OPENAI_URL ?? "http://127.0.0.1:4010";

test.skip(!LIVE, "Set E2E_LIVE_BASE_URL to run the live-mode specs (see README).");
test.use({ baseURL: LIVE });
test.describe.configure({ mode: "serial" });

let page: Page;
let firstConceptUrl = "";

const mockCalls = async (request: APIRequestContext) =>
  (await (await request.get(`${MOCK}/__calls`)).json()) as Array<{ schema: string; repair: boolean; strict: boolean; store: unknown }>;

/** Links in "Your library" on the home page. */
async function libraryLinks(): Promise<string[]> {
  await page.goto("/");
  const library = page.getByRole("region", { name: "Your library" });
  await expect(library.getByText(/Nothing here yet|steps ·/).first()).toBeVisible();
  return library.getByRole("link").evaluateAll((anchors) => anchors.map((a) => a.getAttribute("href") ?? ""));
}

async function generate(topic: string) {
  await page.goto("/");
  await page.getByLabel("What complex concept should we visualize today?").fill(topic);
  await page.getByRole("button", { name: "Visualize" }).click();
}

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage();
});

test.afterAll(async () => {
  await page.close();
});

test("anyone can generate, and the library starts empty", async () => {
  await page.goto("/");
  await expect(page.getByText(/saved in this browser/)).toBeVisible();
  expect(await libraryLinks()).toEqual([]);
});

test("generates, repairs once, saves in the browser, then opens the explanation", async ({ request }) => {
  await request.delete(`${MOCK}/__calls`);
  await generate("Binary search");

  const loader = page.getByTestId("generation-loader");
  await expect(loader).toContainText("Attempt 2 of 3", { timeout: 20_000 });
  await expect(loader).toContainText("Attempt 1 was sent back for revision");
  await expect(loader).toContainText("not a node or panel in this step");

  await page.waitForURL(/\/concept\/[0-9a-f-]{36}$/, { timeout: 30_000 });
  firstConceptUrl = page.url();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Binary search (mock provider)");
  await expect(page.getByText("AI-generated", { exact: true })).toBeVisible();
  // How it was made is the story's last caption.
  for (let i = 0; i < 200 && !(await page.getByRole("button", { name: "Start over" }).isVisible()); i++) {
    await page.keyboard.press("ArrowRight");
  }
  const closing = page.locator("p[aria-live]");
  await expect(closing).toContainText("Generated by AI from “Binary search”");
  await expect(closing).toContainText("on attempt 2");
  await expect(closing).toContainText("saved in this browser only");

  const calls = await mockCalls(request);
  expect(calls.map((c) => `${c.schema}${c.repair ? "+repair" : ""}`)).toEqual([
    "teaching_plan",
    "concept_scenes",
    "concept_scenes+repair",
    "concept_review",
  ]);
  expect(calls.every((c) => c.strict && c.store === false)).toBe(true);
});

test("the saved explanation is in the library and reopens after a reload", async () => {
  expect(await libraryLinks()).toEqual([new URL(firstConceptUrl).pathname]);
  await page.goto(firstConceptUrl);
  await page.reload();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Binary search (mock provider)");
});

test("another browser does not have it", async ({ browser }) => {
  const elsewhere = await browser.newContext();
  const stranger = await elsewhere.newPage();
  await stranger.goto(firstConceptUrl);
  await expect(stranger.getByRole("heading", { name: "This explanation isn't in this browser" })).toBeVisible();
  await elsewhere.close();
});

test("a draft that never passes review is not saved", async ({ request }) => {
  await request.delete(`${MOCK}/__calls`);
  await generate("Binary search always-reject");
  const alert = page.getByTestId("generation-loader").getByRole("alert");
  await expect(alert).toContainText("No draft passed the checks", { timeout: 30_000 });
  await expect(alert).toContainText("The middle index is computed incorrectly.");
  const calls = await mockCalls(request);
  expect(calls.filter((c) => c.schema === "concept_scenes")).toHaveLength(3);
  expect(await libraryLinks()).toHaveLength(1);
});

test("an unsupported topic gets the planner's explanation", async () => {
  await generate("Stock charts unsupported");
  const alert = page.getByTestId("generation-loader").getByRole("alert");
  await expect(alert).toContainText("This topic doesn't fit the format");
  await expect(alert).toContainText("needs charts");
});

test("cancelling stops the server work, saves nothing, and frees the slot", async () => {
  await generate("Binary search slow");
  const loader = page.getByTestId("generation-loader");
  await expect(loader).toContainText("Draft scenes", { timeout: 10_000 });
  await expect(loader.getByText("Drafting scenes from the plan").first()).toBeVisible();
  await loader.getByRole("button", { name: "Cancel" }).click();
  await expect(loader).toContainText("Generation cancelled");

  // The lease is released when the server notices the disconnect.
  await expect
    .poll(async () => {
      const response = await page.request.post("/api/generate", {
        data: { topic: "Binary search", idempotencyKey: randomUUID() },
      });
      const status = response.status();
      if (status === 200) await response.body();
      return status;
    }, { timeout: 10_000 })
    .toBe(200);

  // Generating through the API doesn't touch this browser's library, and the cancelled run saved nothing.
  expect(await libraryLinks()).toHaveLength(1);
});

test("a saved explanation can be deleted from the library", async () => {
  await page.goto("/");
  const library = page.getByRole("region", { name: "Your library" });
  await library.getByRole("button", { name: /Delete “Binary search \(mock provider\)”/ }).click();
  await library.getByRole("button", { name: "Keep" }).click();
  expect(await libraryLinks()).toHaveLength(1);
  await library.getByRole("button", { name: /Delete “Binary search \(mock provider\)”/ }).click();
  await library.getByRole("button", { name: "Delete", exact: true }).click();
  await expect(library.getByText("Nothing here yet")).toBeVisible();
});
