import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { validateConcept } from "@/lib/concept/validate";
import type { Concept } from "@/lib/concept/schema";
import { BUNDLED_FIXTURES } from "@/lib/fixtures";
import { binarySearch } from "@/lib/fixtures/binary-search";
import { raftLeaderElection } from "@/lib/fixtures/raft";
import { compileStory, worldAt } from "@/lib/story/engine";
import { conceptToStory, stepToStory } from "@/lib/story/from-concept";
import { lintStory } from "@/lib/story/lint";

/** Real generated explanations recorded by `npm run eval:prompts`. */
function evalConcepts(): Concept[] {
  const root = path.join(process.cwd(), "evals/runs");
  return readdirSync(root).flatMap((run) => {
    let files: string[] = [];
    try {
      files = readdirSync(path.join(root, run, "concepts"));
    } catch {
      return [];
    }
    return files.flatMap((file) => {
      const checked = validateConcept(JSON.parse(readFileSync(path.join(root, run, "concepts", file), "utf8")));
      return checked.ok ? [checked.concept] : [];
    });
  });
}

const options = { subtitle: "AI-generated explanation", closing: "Generated by AI. Verify important details." };

/** The scene at the end of each concept step: the beats of the explanation chapter that carry a script. */
function stepScenes(concept: Concept) {
  const compiled = compileStory(conceptToStory(concept, options));
  return compiled.beats.filter((b) => b.chapter === 1 && b.beat.run !== undefined).map((b) => worldAt(b.start, b.items, Infinity));
}

describe("conceptToStory", () => {
  const corpus = [...BUNDLED_FIXTURES.map((f) => f.concept), ...evalConcepts()];

  it("has a corpus of real explanations to check", () => {
    expect(corpus.length).toBeGreaterThan(10);
  });

  it("produces stories whose every action refers to something on stage", () => {
    for (const concept of corpus) expect(lintStory(conceptToStory(concept, options), { bounds: false }), concept.title).toEqual([]);
  });

  it("ends each step with exactly that step's nodes, static edges, and messages", () => {
    for (const concept of corpus) {
      const scenes = stepScenes(concept);
      expect(scenes).toHaveLength(concept.steps.length);
      concept.steps.forEach((step, i) => {
        const alive = [...scenes[i]!.live.entries()].filter(([, live]) => live.dying === null);
        const ids = (kind: string) => alive.filter(([, l]) => l.entity.kind === kind).map(([id]) => id).sort();
        expect(ids("node"), `${concept.title}: ${step.id}`).toEqual(step.nodes.map((n) => `n-${n.id}`).sort());
        expect(ids("link"), `${concept.title}: ${step.id}`).toEqual(step.edges.filter((e) => !e.animated).map((e) => `e-${e.id}`).sort());
        expect(scenes[i]!.messages).toHaveLength(step.edges.filter((e) => e.animated).length);
      });
    }
  });

  it("maps visual properties through tokens and keeps text plain", () => {
    const story = conceptToStory(raftLeaderElection, options);
    const steps = story.chapters[1]!.beats;
    expect(steps.every((b) => b.plain)).toBe(true);
    const world = stepScenes(raftLeaderElection)[1]!; // S5 crashed
    const s5 = world.live.get("n-s5")!.entity;
    expect(s5).toMatchObject({ kind: "node", fill: "gray", desc: ["S5 offline"] });
    expect(story.chapters[0]!.beats[0]!.title).toEqual({ heading: raftLeaderElection.title, sub: options.subtitle });
    expect(steps.at(-1)).toMatchObject({ say: options.closing });
  });

  it("keeps squares, for data such as array cells", () => {
    const world = stepScenes(binarySearch)[0]!;
    const shapes = [...world.live.values()].filter((l) => l.entity.kind === "node").map((l) => (l.entity as { shape?: string }).shape);
    expect(shapes).toContain("square");
  });

  it("builds a one-step scene for thumbnails", () => {
    const step = raftLeaderElection.steps[3]!;
    const compiled = compileStory(stepToStory(step));
    const world = worldAt(compiled.beats[0]!.start, compiled.beats[0]!.items, Infinity);
    expect([...world.live.keys()].filter((id) => id.startsWith("n-"))).toHaveLength(step.nodes.length);
    expect(world.messages).toHaveLength(step.edges.filter((e) => e.animated).length);
  });
});
