import { validateConcept } from "@/lib/concept/validate";
import { BUNDLED_FIXTURES } from "./index";

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;

/** SQL that upserts every bundled fixture as a public, curated concept. */
export function buildSeedSql(): string {
  const rows = BUNDLED_FIXTURES.map(({ slug, concept }) => {
    const result = validateConcept(concept);
    if (!result.ok) {
      throw new Error(`Fixture ${slug} is invalid: ${JSON.stringify(result.issues)}`);
    }
    const json = JSON.stringify(concept);
    if (json.includes("$seed$")) throw new Error(`Fixture ${slug} contains the dollar-quote tag`);
    return `  (${sqlString(concept.id)}, ${sqlString(concept.title)}, ${sqlString(concept.description)}, ${concept.schemaVersion}, $seed$${json}$seed$::jsonb, 'public', 'curated')`;
  });

  return `-- Generated by \`npm run seed:generate\` from lib/fixtures. Do not edit by hand.
-- Curated, public explanations. Safe to re-run.
insert into public.concepts (id, title, description, schema_version, content, visibility, origin)
values
${rows.join(",\n")}
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  schema_version = excluded.schema_version,
  content = excluded.content,
  visibility = excluded.visibility,
  origin = excluded.origin;
`;
}
