"use client";

import Link from "next/link";
import { useMemo, useSyncExternalStore } from "react";
import type { Concept } from "@/lib/concept/schema";
import { findExplanation, readLibraryRaw, readSupplementsSnapshot, subscribeLibrary, supplementsFor, supplementsRawOf } from "@/lib/library";
import { conceptStories } from "@/lib/story/from-concept";
import { ExplorePanel } from "./story/ExplorePanel";
import { StepTools } from "./story/StepTools";
import { StoryMessage } from "./story/StoryMessage";
import { StoryPlayer } from "./story/StoryPlayer";

const dateFormat = new Intl.DateTimeFormat("en", { dateStyle: "medium" });

/** How an AI-generated explanation was made, as the story's last caption. */
export function provenanceCaption(concept: Concept, topic: string, createdAt: string, attempts: number): string {
  const p = concept.provenance;
  const when = dateFormat.format(new Date(createdAt));
  const made =
    p?.request.kind === "source"
      ? `Generated by AI from material you supplied (“${topic}”) on ${when}.`
      : p?.request.kind === "example"
        ? `An example generated by AI on ${when}, made up to illustrate one step of another explanation.`
        : `Generated by AI from “${topic}” on ${when}.`;
  const checks = `It passed automated structure checks and an AI review${attempts > 1 ? ` on attempt ${attempts}` : ""}.`;
  const sources = p?.sourcesConsulted
    ? "Claims marked as stated in your material were matched to excerpts of it, but the material was not checked against other sources, and automated review is not proof of accuracy."
    : "Automated review is not proof of accuracy and no sources were consulted, so verify important details.";
  return [made, checks, sources].join(" ");
}

/** An explanation generated in this browser, read from its localStorage library. */
export function SavedExplanation({ id, exploreAvailable, exampleId }: { id: string; exploreAvailable: boolean; exampleId?: string }) {
  // `undefined` on the server and during hydration: storage is only readable in the browser.
  const raw = useSyncExternalStore(subscribeLibrary, readLibraryRaw, () => undefined);
  const supplementsSnapshot = useSyncExternalStore(subscribeLibrary, readSupplementsSnapshot, () => undefined);
  const found = useMemo(() => (raw === undefined ? undefined : findExplanation(raw, id)), [raw, id]);
  const example = useMemo(() => {
    if (!exampleId || supplementsSnapshot === undefined) return undefined;
    const supplement = supplementsFor(supplementsRawOf(supplementsSnapshot), id).find((s) => s.id === exampleId);
    return supplement?.kind === "example" ? supplement : null;
  }, [exampleId, supplementsSnapshot, id]);

  const shown = exampleId ? (example ? example.concept : example) : found ? found.item.concept : found;
  const stories = useMemo(() => {
    if (!found || !shown) return shown === undefined || found === undefined ? undefined : null;
    const { item, stored } = found;
    const closing = exampleId
      ? `${provenanceCaption(shown, item.topic, example!.createdAt, 1)} It is kept in this browser with the explanation it belongs to.`
      : `${provenanceCaption(shown, item.topic, item.createdAt, item.attempts)} ${
          stored ? "It is saved in this browser only." : "This browser could not save it, so it is gone when you leave this page."
        }`;
    return conceptStories(shown, { subtitle: exampleId ? "AI-generated example" : "AI-generated explanation", closing });
  }, [found, shown, exampleId, example]);

  if (stories === undefined) return <div aria-busy="true" aria-label="Loading the explanation" className="min-h-dvh bg-white" />;
  if (stories === null || !found || !shown) {
    return exampleId && found ? (
      <StoryMessage title="This example isn't in this browser" action={{ href: `/concept/${id}`, label: "Back to the explanation" }}>
        Examples are kept in the browser that asked for them. It may have been removed.
      </StoryMessage>
    ) : (
      <StoryMessage title="This explanation isn't in this browser" action={{ href: "/", label: "Back to the home page" }}>
        Explanations are saved in the browser that generated them, so their links don&apos;t work in other browsers, other
        devices, or private windows. It may also have been deleted from this browser&apos;s library.
      </StoryMessage>
    );
  }
  const concept = shown;
  const topic = found.item.topic;
  return (
    <StoryPlayer
      story={stories.landscape}
      portrait={stories.portrait}
      label={exampleId ? "AI-generated example" : found.stored ? "AI-generated" : "AI-generated · not saved"}
      tools={({ step, onDrawer }) => (
        <>
          {exampleId ? (
            <Link href={`/concept/${id}`} className="hidden h-[30px] items-center rounded-[4px] border border-[#ccc] bg-white px-2 text-[13px] text-[#333] hover:bg-[#ebebeb] sm:inline-flex">
              ← Back to the explanation
            </Link>
          ) : null}
          <StepTools
            concept={concept}
            step={step}
            origin="generated"
            onDrawer={onDrawer}
            explore={
              exploreAvailable && !exampleId
                ? (current) => <ExplorePanel concept={concept} topic={topic} step={current} examplePath={(sid) => `/concept/${id}/example/${sid}`} />
                : undefined
            }
          />
        </>
      )}
    />
  );
}
