"use client";

import { useMemo, useSyncExternalStore } from "react";
import { findExplanation, readLibraryRaw, subscribeLibrary } from "@/lib/library";
import { conceptToStory } from "@/lib/story/from-concept";
import { StoryMessage } from "./story/StoryMessage";
import { StoryPlayer } from "./story/StoryPlayer";

const dateFormat = new Intl.DateTimeFormat("en", { dateStyle: "medium" });

/** An explanation generated in this browser, read from its localStorage library. */
export function SavedExplanation({ id }: { id: string }) {
  // `undefined` on the server and during hydration: storage is only readable in the browser.
  const raw = useSyncExternalStore(subscribeLibrary, readLibraryRaw, () => undefined);
  const found = useMemo(() => (raw === undefined ? undefined : findExplanation(raw, id)), [raw, id]);

  const story = useMemo(() => {
    if (!found) return found;
    const { item, stored } = found;
    return conceptToStory(item.concept, {
      subtitle: "AI-generated explanation",
      closing: [
        `Generated by AI from “${item.topic}” on ${dateFormat.format(new Date(item.createdAt))}.`,
        `It passed automated structure checks and an AI review${item.attempts > 1 ? ` on attempt ${item.attempts}` : ""}.`,
        "Automated review is not proof of accuracy and no sources were consulted, so verify important details.",
        stored
          ? "It is saved in this browser only."
          : "This browser could not save it, so it is gone when you leave this page.",
      ].join(" "),
    });
  }, [found]);

  if (story === undefined) return <div aria-busy="true" aria-label="Loading the explanation" className="min-h-dvh bg-white" />;
  if (story === null) {
    return (
      <StoryMessage title="This explanation isn't in this browser" action={{ href: "/", label: "Back to the home page" }}>
        Explanations are saved in the browser that generated them, so their links don&apos;t work in other browsers, other
        devices, or private windows. It may also have been deleted from this browser&apos;s library.
      </StoryMessage>
    );
  }
  return <StoryPlayer story={story} label={found?.stored ? "AI-generated" : "AI-generated · not saved"} />;
}
