"use client";

import { useMemo, useSyncExternalStore } from "react";
import { parseUnsaved, readUnsavedRaw } from "@/lib/generation/unsaved";
import { conceptToStory } from "@/lib/story/from-concept";
import { StoryMessage } from "./story/StoryMessage";
import { StoryPlayer } from "./story/StoryPlayer";

const subscribe = (onChange: () => void) => {
  window.addEventListener("storage", onChange);
  return () => window.removeEventListener("storage", onChange);
};

/** The explanation this tab generated without a database (see lib/generation/unsaved.ts). */
export function UnsavedPreview() {
  // `undefined` on the server and during hydration: storage is only readable in the browser.
  const raw = useSyncExternalStore(subscribe, readUnsavedRaw, () => undefined);
  const story = useMemo(() => {
    if (raw === undefined) return undefined;
    const unsaved = parseUnsaved(raw);
    if (!unsaved) return null;
    return conceptToStory(unsaved.concept, {
      subtitle: "AI-generated explanation (not saved)",
      closing: `Generated by AI from “${unsaved.topic}”. No database is configured, so it is not saved: it lives only in this tab and is gone when you close it. Automated review is not proof of accuracy and no sources were consulted, so verify important details.`,
    });
  }, [raw]);

  if (story === undefined) return <div aria-busy="true" aria-label="Loading the explanation" className="min-h-dvh bg-white" />;
  if (story === null) {
    return (
      <StoryMessage title="Nothing to show here" action={{ href: "/", label: "Generate an explanation" }}>
        Without a database, a generated explanation lives only in the browser tab that created it, and it&apos;s gone once that
        tab closes.
      </StoryMessage>
    );
  }
  return <StoryPlayer story={story} label="AI-generated · not saved" />;
}
